### ISSUE TITLE
 Is there a Windows version of this environment?

### ISSUE THREAD

**Issue by ExitPath** [leekwoon/nav-gym#1]
Hello, I am very interested in this navigation environment. Is there a Windows version of this environment? Alternatively, how does this environment work under Windows?

**Comment by leekwoon** [comment]
Hi, Thank you for showing an interest in our navigation environment!

Although we haven't tested it on Windows,  we think it should work fine. You might be able to skip the installation procedure related to ROS.

The primary benefit of using Ubuntu is that it allows for fast and interactive RVIZ visualization. However, our simulator still offers a rendering function supported by the cv2 package, so you can visualize the simulation.
