### ISSUE TITLE
ResourceNotFound: dxp2d

### ISSUE THREAD

**Issue by Lin-3** [leekwoon/nav-gym#2]
Hello, my ros version is ros-kinetic. And I install this project with ROS-supported.
But when I run 'roslaunch nav_gym view_robot.launch', the error 'ResourceNotFound: dxp2d' occur.
The code in view_robot.launch is '<node name="rviz” pkg="rviz" type="rviz" args="-d $(find dxp2d)/rviz/robot. viz" output="screen">'.
It seems that it is looking for the package dxp2d, also there is 'from dxp2d_env import ...' in the keti_robot.py. 
But I couldn't find dxp2d in this project.
How can I solve this problem?

**Comment by leekwoon** [comment]
Hello,

Thank you for pointing out this issue. We've identified the problem and made adjustments. You can check the detailed changes [here](https://github.com/leekwoon/nav-gym/commit/e436516a17ad8bbf0fa15344e3522f5c644859fc). 

Please update your local branch with the new changes.

**Comment by Lin-3** [comment]
> Hello,
> 
> Thank you for pointing out this issue. We've identified the problem and made adjustments. You can check the detailed changes [here](https://github.com/leekwoon/nav-gym/commit/e436516a17ad8bbf0fa15344e3522f5c644859fc).
> 
> Please update your local branch with the new changes.

Thanks for your help！
I update the project and run the commands in the readme.
I got the following result.
![QQ截图20230609214541](https://github.com/leekwoon/nav-gym/assets/75254670/8b21c94c-5ae1-439b-9f5e-ef78b42596bd)
But it seems that the 'env.step(action)' doesn't work.
What is the correct visualization result following the readme.md?

**Comment by leekwoon** [comment]
The correct visualization result is

![Screenshot from 2023-06-09 23-10-25](https://github.com/leekwoon/nav-gym/assets/14149631/0c749ce6-cfea-48c3-8550-e39b7e8faa5e)

By the way, is the simulation working well without RViz? (like following commands)

If it is working well, then it would be a ROS-related problem. Were there any error messages in the terminal?

```
import gym
import nav_gym_env

env = gym.make("NavGym-v0")
obs = env.reset()

done = False
while not done:
    action = env.action_space.sample() # Your agent code here
    obs, reward, done, info = env.step(action)
    env.render()
```

**Comment by Lin-3** [comment]
> The correct visualization result is
> 
> ![Screenshot from 2023-06-09 23-10-25](https://user-images.githubusercontent.com/14149631/244716207-0c749ce6-cfea-48c3-8550-e39b7e8faa5e.png)
> 
> By the way, is the simulation working well without RViz? (like following commands)
> 
> If it is working well, then it would be a ROS-related problem. Were there any error messages in the terminal?
> 
> ```
> import gym
> import nav_gym_env
> 
> env = gym.make("NavGym-v0")
> obs = env.reset()
> 
> done = False
> while not done:
>     action = env.action_space.sample() # Your agent code here
>     obs, reward, done, info = env.step(action)
>     env.render()
> ```

I got the result like this, is it correct?
![image](https://github.com/leekwoon/nav-gym/assets/75254670/ad97e78c-5301-4862-adf4-76cad05cc16c)

**Comment by leekwoon** [comment]
Yes, It is correct result without RViz.
