### ISSUE TITLE
struct.error: unpack requires a buffer of 12 bytes

### ISSUE THREAD

**Issue by Lin-3** [leekwoon/nav-gym#3]
Hello!
When I follow the readme to use RViz visualization, an error occurs.
![WAPA@WV0 1B1N{HA`G@_7JA](https://github.com/leekwoon/nav-gym/assets/75254670/0842fa7b-a330-43eb-bc43-0c5aa560feef)
I find the function deserialize(str) and print out the input, and find that the input is empty("").
Also, the code has a note on it :"raise genpy. DeserializationError(e) # most likely buffer underfill".
This problem causes the bug that the env couldn't step.
How can I solve this problem?

**Comment by leekwoon** [comment]
I think..  
Some third-party packages  have been taken from https://github.com/srl-freiburg/pedsim_ros/tree/melodic-dev (which only supports ros-melodic). I think this part might be the problem. I would recommend testing in the ROS melodic environment.
