### ISSUE TITLE
Controller Spawner couldn‘t find the expected controller_manager ROS interface.

### ISSUE THREAD

**Issue by Lin-3** [leekwoon/nav-gym#4]
Hello!
When I run the command "roslaunch nav_gym start_nav_gym.launch", warning "Controller Spawner couldn‘t find the expected controller_manager ROS interface." appears.
I have confirmed that 'controller_manager' has been installed.
I have google this problem and try some possible solutions but none of them work.
The answer int the following page mentions the problem of the namespace.
https://answers.ros.org/question/214712/gazebo-controller-spawner-warning/
Does this problem result from it?
Hope you can help me.
![IOESIFG3__KHIZ}V~X~F37F](https://github.com/leekwoon/nav-gym/assets/75254670/1e3f2d51-81f9-4b6d-92f6-cfd95eceb1eb)

**Comment by leekwoon** [comment]
Hi!, 

Does above warning result in problem in simulation?

And did you suceed in visualizing with RViz?
```
roslaunch nav_gym view_robot.launch
```

**Comment by Lin-3** [comment]
> Hi!,
> 
> Does above warning result in problem in simulation?
> 
> And did you suceed in visualizing with RViz?
> 
> ```
> roslaunch nav_gym view_robot.launch
> ```

In fact, error occurs when I try to visualize with RViz.
![image](https://github.com/leekwoon/nav-gym/assets/75254670/b7aa1f71-a7e6-450b-aa8a-4c1f031b86e1)
And I guess this waring in "start_nav_gym.launch" may be the reason.

**Comment by leekwoon** [comment]
I guess the error is related to some third party ROS packages. 

Which version of ROS are you using now?

**Comment by Lin-3** [comment]
> I guess the error is related to some third party ROS packages.
> 
> Which version of ROS are you using now?

Kinetic.

**Comment by kun1224** [comment]
Do you solve the problem?I encounter the same case,can you give me some advice.
